### ISSUE TITLE
Reminders being sent to carts with zero products

### ISSUE THREAD

**Issue by damonadigital** [verbb/abandoned-cart#78]
We've noticed on one of our websites that some customers are receiving Abandoned Cart notifications when they have no items in their basket. Is there any known cause of this behaviour?

<img width="1155" alt="Screenshot 2024-03-11 at 15 47 32" src="https://github.com/mediabeastnz/craft-commerce-abandoned-cart/assets/133118200/a3bb74de-c6e1-4bd0-92de-3bdcac7eabab">

**Comment by engram-design** [comment]
So I don't _believe_ that should be possible with the logic we have, which is checking if the `totalPrice` for the order is greater than zero. Feel free to re-open and comment on your Craft, Commerce and Abandoned Cart versions.
